// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.Cpr.ConsoleSample.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class LegalGuardian
    {
        /// <summary>
        /// Initializes a new instance of the LegalGuardian class.
        /// </summary>
        public LegalGuardian()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the LegalGuardian class.
        /// </summary>
        public LegalGuardian(string id = default(string), string cpr = default(string), string relation = default(string))
        {
            Id = id;
            Cpr = cpr;
            Relation = relation;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cpr")]
        public string Cpr { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "relation")]
        public string Relation { get; set; }

    }
}
