// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.Cpr.ConsoleSample.Client
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for CprClient.
    /// </summary>
    public static partial class CprClientExtensions
    {
            /// <summary>
            /// Gets citizen data by CPR
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// LoGIC subscription ID
            /// </param>
            /// <param name='cpr'>
            /// Personal identification number of danish citizen
            /// </param>
            /// <param name='configurationId'>
            /// Identifier that represents CPR environment and associated configuration
            /// which this request will be sent with.
            /// </param>
            public static Citizen SubscriptionsBySubscriptionIdCprByCprByCprGet(this ICprClient operations, System.Guid subscriptionId, string cpr, System.Guid? configurationId = default(System.Guid?))
            {
                return operations.SubscriptionsBySubscriptionIdCprByCprByCprGetAsync(subscriptionId, cpr, configurationId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Gets citizen data by CPR
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// LoGIC subscription ID
            /// </param>
            /// <param name='cpr'>
            /// Personal identification number of danish citizen
            /// </param>
            /// <param name='configurationId'>
            /// Identifier that represents CPR environment and associated configuration
            /// which this request will be sent with.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<Citizen> SubscriptionsBySubscriptionIdCprByCprByCprGetAsync(this ICprClient operations, System.Guid subscriptionId, string cpr, System.Guid? configurationId = default(System.Guid?), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.SubscriptionsBySubscriptionIdCprByCprByCprGetWithHttpMessagesAsync(subscriptionId, cpr, configurationId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Gets citizen data by ID
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// LoGIC subscription ID
            /// </param>
            /// <param name='id'>
            /// ID of danish citizen
            /// </param>
            /// <param name='configurationId'>
            /// Identifier that represents CPR environment and associated configuration
            /// which this request will be sent with.
            /// </param>
            public static Citizen SubscriptionsBySubscriptionIdCprByIdGet(this ICprClient operations, System.Guid subscriptionId, System.Guid id, System.Guid? configurationId = default(System.Guid?))
            {
                return operations.SubscriptionsBySubscriptionIdCprByIdGetAsync(subscriptionId, id, configurationId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Gets citizen data by ID
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// LoGIC subscription ID
            /// </param>
            /// <param name='id'>
            /// ID of danish citizen
            /// </param>
            /// <param name='configurationId'>
            /// Identifier that represents CPR environment and associated configuration
            /// which this request will be sent with.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<Citizen> SubscriptionsBySubscriptionIdCprByIdGetAsync(this ICprClient operations, System.Guid subscriptionId, System.Guid id, System.Guid? configurationId = default(System.Guid?), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.SubscriptionsBySubscriptionIdCprByIdGetWithHttpMessagesAsync(subscriptionId, id, configurationId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Retrieves Cpr configuration assigned to the logic subscription
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// </param>
            /// <param name='configurationId'>
            /// </param>
            public static CprConfiguration SubscriptionsBySubscriptionIdCprConfigurationsByConfigurationIdGet(this ICprClient operations, System.Guid subscriptionId, System.Guid configurationId)
            {
                return operations.SubscriptionsBySubscriptionIdCprConfigurationsByConfigurationIdGetAsync(subscriptionId, configurationId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Retrieves Cpr configuration assigned to the logic subscription
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// </param>
            /// <param name='configurationId'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<CprConfiguration> SubscriptionsBySubscriptionIdCprConfigurationsByConfigurationIdGetAsync(this ICprClient operations, System.Guid subscriptionId, System.Guid configurationId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.SubscriptionsBySubscriptionIdCprConfigurationsByConfigurationIdGetWithHttpMessagesAsync(subscriptionId, configurationId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Adds or updates existing cpr configuration and uploads certificate file to
            /// the Azure Key Vault
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// </param>
            /// <param name='configurationId'>
            /// </param>
            /// <param name='environment'>
            /// Possible values include: 'production', 'test'
            /// </param>
            public static CprConfiguration SubscriptionsBySubscriptionIdCprConfigurationsByConfigurationIdPut(this ICprClient operations, System.Guid subscriptionId, System.Guid configurationId, string environment = default(string))
            {
                return operations.SubscriptionsBySubscriptionIdCprConfigurationsByConfigurationIdPutAsync(subscriptionId, configurationId, environment).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Adds or updates existing cpr configuration and uploads certificate file to
            /// the Azure Key Vault
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// </param>
            /// <param name='configurationId'>
            /// </param>
            /// <param name='environment'>
            /// Possible values include: 'production', 'test'
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<CprConfiguration> SubscriptionsBySubscriptionIdCprConfigurationsByConfigurationIdPutAsync(this ICprClient operations, System.Guid subscriptionId, System.Guid configurationId, string environment = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.SubscriptionsBySubscriptionIdCprConfigurationsByConfigurationIdPutWithHttpMessagesAsync(subscriptionId, configurationId, environment, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Retrieves all Cpr configurations assigned to the logic subscription
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// </param>
            public static CprConfiguration SubscriptionsBySubscriptionIdCprConfigurationsGet(this ICprClient operations, System.Guid subscriptionId)
            {
                return operations.SubscriptionsBySubscriptionIdCprConfigurationsGetAsync(subscriptionId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Retrieves all Cpr configurations assigned to the logic subscription
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<CprConfiguration> SubscriptionsBySubscriptionIdCprConfigurationsGetAsync(this ICprClient operations, System.Guid subscriptionId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.SubscriptionsBySubscriptionIdCprConfigurationsGetWithHttpMessagesAsync(subscriptionId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Adds new CPR configuration and uploads certificate file to the Azure Key
            /// Vault
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// </param>
            /// <param name='environment'>
            /// Possible values include: 'production', 'test'
            /// </param>
            public static CprConfiguration SubscriptionsBySubscriptionIdCprConfigurationsPost(this ICprClient operations, System.Guid subscriptionId, string environment = default(string))
            {
                return operations.SubscriptionsBySubscriptionIdCprConfigurationsPostAsync(subscriptionId, environment).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Adds new CPR configuration and uploads certificate file to the Azure Key
            /// Vault
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// </param>
            /// <param name='environment'>
            /// Possible values include: 'production', 'test'
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<CprConfiguration> SubscriptionsBySubscriptionIdCprConfigurationsPostAsync(this ICprClient operations, System.Guid subscriptionId, string environment = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.SubscriptionsBySubscriptionIdCprConfigurationsPostWithHttpMessagesAsync(subscriptionId, environment, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
