// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.Cpr.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Address
    {
        /// <summary>
        /// Initializes a new instance of the Address class.
        /// </summary>
        public Address()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Address class.
        /// </summary>
        public Address(string buildingNo = default(string), string city = default(string), string municipalityCode = default(string), string municipalityName = default(string), string roadCode = default(string), string darAddress = default(string), string floor = default(string), string houseNo = default(string), string postDistrict = default(string), string postCode = default(string), string doorNo = default(string), string roadAddressingName = default(string), bool? isCurrent = default(bool?), System.DateTime? movedTo = default(System.DateTime?), System.DateTime? movedAway = default(System.DateTime?), bool? vacatingDateUncertainityMarking = default(bool?), string careOfAddress = default(string))
        {
            BuildingNo = buildingNo;
            City = city;
            MunicipalityCode = municipalityCode;
            MunicipalityName = municipalityName;
            RoadCode = roadCode;
            DarAddress = darAddress;
            Floor = floor;
            HouseNo = houseNo;
            PostDistrict = postDistrict;
            PostCode = postCode;
            DoorNo = doorNo;
            RoadAddressingName = roadAddressingName;
            IsCurrent = isCurrent;
            MovedTo = movedTo;
            MovedAway = movedAway;
            VacatingDateUncertainityMarking = vacatingDateUncertainityMarking;
            CareOfAddress = careOfAddress;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "buildingNo")]
        public string BuildingNo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "city")]
        public string City { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "municipalityCode")]
        public string MunicipalityCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "municipalityName")]
        public string MunicipalityName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "roadCode")]
        public string RoadCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "darAddress")]
        public string DarAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "floor")]
        public string Floor { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "houseNo")]
        public string HouseNo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "postDistrict")]
        public string PostDistrict { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "postCode")]
        public string PostCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "doorNo")]
        public string DoorNo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "roadAddressingName")]
        public string RoadAddressingName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isCurrent")]
        public bool? IsCurrent { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "movedTo")]
        public System.DateTime? MovedTo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "movedAway")]
        public System.DateTime? MovedAway { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "vacatingDateUncertainityMarking")]
        public bool? VacatingDateUncertainityMarking { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "careOfAddress")]
        public string CareOfAddress { get; set; }

    }
}
