// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.Cpr.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Children
    {
        /// <summary>
        /// Initializes a new instance of the Children class.
        /// </summary>
        public Children()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Children class.
        /// </summary>
        public Children(string cpr = default(string))
        {
            Cpr = cpr;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cpr")]
        public string Cpr { get; set; }

    }
}
