// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.Cpr.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SpouseDetails
    {
        /// <summary>
        /// Initializes a new instance of the SpouseDetails class.
        /// </summary>
        public SpouseDetails()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SpouseDetails class.
        /// </summary>
        public SpouseDetails(string firstName = default(string), string lastName = default(string), string cpr = default(string))
        {
            FirstName = firstName;
            LastName = lastName;
            Cpr = cpr;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "firstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastName")]
        public string LastName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cpr")]
        public string Cpr { get; set; }

    }
}
